#!/bin/sh
#
# Given a pristine system this will install the SFTP service,
# and create a pair of helpers for controlling the service itself.
#
#



#
#  Get our starting directory.
#
dir=`pwd`

rm -rf /usr/local/lib/python2.7/dist-packages/*swift*     || true
rm -rf /usr/local/lib/python2.7/dist-packages/*cloudfs*   || true


#
#  Install the swift-client.
#
cd python-swiftclient && python setup.py install

#
#  Reset the PWD and install the cloudfs library.
#
cd "$dir"
pip install ftp-cloudfs/

#
#  Reset the PWD and install the sftp library.
#
cd "$dir"
pip install sftpcloudfs/



#
#  Create two wrapper-scripts
#
cat > /usr/local/bin/sftp-start <<EOF
#!/bin/sh
/usr/sbin/service sftp start
EOF
cat > /usr/local/bin/sftp-stop <<EOF
#!/bin/sh
/usr/sbin/service sftp stop
/usr/bin/killall -9 sftpcloudfs 2>/dev/null >/dev/null
EOF

#
# Ensure they're executable
#
chmod 755 /usr/local/bin/sftp-start /usr/local/bin/sftp-stop